# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import secure_aggregation_pb2 as secure__aggregation__pb2


class AggregatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateParameters = channel.unary_unary(
                '/secure_aggregation.Aggregator/UpdateParameters',
                request_serializer=secure__aggregation__pb2.ParametersRequest.SerializeToString,
                response_deserializer=secure__aggregation__pb2.ParametersReply.FromString,
                )


class AggregatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParameters,
                    request_deserializer=secure__aggregation__pb2.ParametersRequest.FromString,
                    response_serializer=secure__aggregation__pb2.ParametersReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secure_aggregation.Aggregator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Aggregator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/secure_aggregation.Aggregator/UpdateParameters',
            secure__aggregation__pb2.ParametersRequest.SerializeToString,
            secure__aggregation__pb2.ParametersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
