# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secure_aggregation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='secure_aggregation.proto',
  package='secure_aggregation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18secure_aggregation.proto\x12\x12secure_aggregation\"\xcb\x01\n\x11ParametersRequest\x12\x1c\n\x14\x65ncrypted_parameters\x18\x01 \x01(\x0c\x12\x19\n\x11num_of_parameters\x18\x02 \x01(\r\x12 \n\x18num_of_sparse_parameters\x18\x03 \x01(\r\x12\x12\n\nclient_ids\x18\x04 \x03(\r\x12\r\n\x05sigma\x18\x05 \x01(\x02\x12\x10\n\x08\x63lipping\x18\x06 \x01(\x02\x12\r\n\x05\x61lpha\x18\x07 \x01(\x02\x12\x17\n\x0f\x61ggregation_alg\x18\x08 \x01(\r\"E\n\x0fParametersReply\x12\x1a\n\x12updated_parameters\x18\x01 \x03(\x02\x12\x16\n\x0e\x65xecution_time\x18\x02 \x01(\x02\x32l\n\nAggregator\x12^\n\x10UpdateParameters\x12%.secure_aggregation.ParametersRequest\x1a#.secure_aggregation.ParametersReplyb\x06proto3'
)




_PARAMETERSREQUEST = _descriptor.Descriptor(
  name='ParametersRequest',
  full_name='secure_aggregation.ParametersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_parameters', full_name='secure_aggregation.ParametersRequest.encrypted_parameters', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_of_parameters', full_name='secure_aggregation.ParametersRequest.num_of_parameters', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_of_sparse_parameters', full_name='secure_aggregation.ParametersRequest.num_of_sparse_parameters', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_ids', full_name='secure_aggregation.ParametersRequest.client_ids', index=3,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sigma', full_name='secure_aggregation.ParametersRequest.sigma', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clipping', full_name='secure_aggregation.ParametersRequest.clipping', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='secure_aggregation.ParametersRequest.alpha', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregation_alg', full_name='secure_aggregation.ParametersRequest.aggregation_alg', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=252,
)


_PARAMETERSREPLY = _descriptor.Descriptor(
  name='ParametersReply',
  full_name='secure_aggregation.ParametersReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='updated_parameters', full_name='secure_aggregation.ParametersReply.updated_parameters', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='execution_time', full_name='secure_aggregation.ParametersReply.execution_time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['ParametersRequest'] = _PARAMETERSREQUEST
DESCRIPTOR.message_types_by_name['ParametersReply'] = _PARAMETERSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParametersRequest = _reflection.GeneratedProtocolMessageType('ParametersRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERSREQUEST,
  '__module__' : 'secure_aggregation_pb2'
  # @@protoc_insertion_point(class_scope:secure_aggregation.ParametersRequest)
  })
_sym_db.RegisterMessage(ParametersRequest)

ParametersReply = _reflection.GeneratedProtocolMessageType('ParametersReply', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERSREPLY,
  '__module__' : 'secure_aggregation_pb2'
  # @@protoc_insertion_point(class_scope:secure_aggregation.ParametersReply)
  })
_sym_db.RegisterMessage(ParametersReply)



_AGGREGATOR = _descriptor.ServiceDescriptor(
  name='Aggregator',
  full_name='secure_aggregation.Aggregator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=325,
  serialized_end=433,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateParameters',
    full_name='secure_aggregation.Aggregator.UpdateParameters',
    index=0,
    containing_service=None,
    input_type=_PARAMETERSREQUEST,
    output_type=_PARAMETERSREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGGREGATOR)

DESCRIPTOR.services_by_name['Aggregator'] = _AGGREGATOR

# @@protoc_insertion_point(module_scope)
